# Generated by Django 2.2.3 on 2019-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('opt1', models.TextField()),
                ('opt2', models.TextField()),
                ('collect', models.IntegerField(choices=[(1, '1번'), (2, '2번')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hashcode', models.CharField(max_length=50)),
                ('quiz_url', models.URLField()),
            ],
        ),
    ]
