# Generated by Django 2.2.3 on 2019-07-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='collect',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='opt2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
    ]
