# Generated by Django 2.2.3 on 2019-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190723_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quiz_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
