# Generated by Django 2.2.3 on 2019-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190723_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='opt1',
            field=models.CharField(default='질문1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='opt2',
            field=models.CharField(default='대답1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='대답2', max_length=50),
            preserve_default=False,
        ),
    ]
