# Generated by Django 2.2.3 on 2019-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190723_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(choices=[(0, '미정'), (1, '1번'), (2, '2번')], default=0),
        ),
    ]
