# Generated by Django 2.2.3 on 2019-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190723_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
