# Generated by Django 2.2.3 on 2019-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190724_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer',
            field=models.CharField(blank=True, default='0000000000', max_length=10, null=True),
        ),
    ]
