# Generated by Django 2.2.3 on 2019-07-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190724_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
