# Generated by Django 2.2.3 on 2019-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190724_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quiz_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
