# Generated by Django 2.2.3 on 2019-07-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190724_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User')),
            ],
        ),
    ]
