# Generated by Django 2.2.3 on 2019-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_challenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenger',
            name='result',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
