# Generated by Django 2.2.3 on 2019-07-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190724_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenger',
            options={'ordering': ['-result', 'name']},
        ),
    ]
